# Generated by Django 4.2.7 on 2023-12-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0002_alter_product_slug_alter_productattribute_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
