# Generated by Django 4.2.7 on 2024-01-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0003_rename_first_name_order_merchant_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
