# Generated by Django 4.2.7 on 2023-12-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0003_remove_product_color_remove_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='num_used',
            new_name='used',
        ),
    ]
