# Generated by Django 4.2.7 on 2024-01-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0004_order_merchant_order_payment_order_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_date',
        ),
    ]
