# Generated by Django 4.2.7 on 2023-12-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0004_rename_num_used_coupon_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/%Y/%m/%d'),
        ),
    ]
