# Generated by Django 4.2.7 on 2023-12-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0006_product_users_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='discountprice',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
