# Generated by Django 4.2.7 on 2024-01-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0009_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_data3',
            field=models.BooleanField(default=False),
        ),
    ]
