# Generated by Django 4.2.7 on 2024-01-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moontag_app', '0012_chatroom_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chatroom',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
